syntax = "proto3";
package ddt;

import "common.proto";

// ---- 房间 ----
message JoinRoomRequest {
  uint32   room_id = 1;
  TeamSide team    = 2;
}

message JoinRoomResponse {
  bool   ok       = 1;
  uint32 room_id  = 2;
  string msg      = 3;
}

message RoomListRequest {}

message RoomListResponse {
  repeated RoomInfo rooms = 1;
}

message CreateRoomRequest {
  string room_name = 1;
}

message CreateRoomResponse {
  bool   ok       = 1;
  uint32 room_id  = 2;
  string msg      = 3;
}

message RoomUpdateNotify {
  RoomInfo room_info = 1;
}

message ReadyRequest {
  bool ready = 1;
}

message ReadyNotify {
  uint32 player_id = 1;
  bool   ready     = 2;
}

message LeaveRoomRequest {}

// 队伍切换
message SwitchTeamRequest {
  TeamSide team = 1;
}

message SwitchTeamResponse {
  bool     ok  = 1;
  string   msg = 2;
  TeamSide team = 3;
}

// 双方就绪，游戏开始
message RoomReadyNotify {
  uint32      room_id        = 1;
  PlayerState player1        = 2;
  PlayerState player2        = 3;
  float       wind           = 4;
  uint32      first_turn_id  = 5;
}
